DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.static import serve
from .settings import DEBUG,MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
]

if DEBUG:
    urlpatterns+=[
        re_path(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
    ]

blog/urls.py
from django.urls import path
from . import views as blogviews
from django.conf.urls import url

app_name='blog'
urlpatterns = [
    url(r'^$', blogviews.article_list),
    path('article_list/', blogviews.article_list,name='article_list'),
    path('article_create/', blogviews.article_create, name='article_create'),
    path('article_detail/<int:id>/', blogviews.article_detail, name='article_detail'),
    path('article_delete/<int:id>/', blogviews.article_delete, name='article_delete'),
    path('article_update/<int:id>/', blogviews.article_update, name='article_update'),

    path('post_comment/<int:article_id>/', blogviews.post_comment, name='post_comment'),

    path('user_login/', blogviews.user_login, name='user_login'),
    path('user_logout/', blogviews.user_logout, name='user_logout'),
    path('user_register/', blogviews.user_register, name='user_register'),
    path('user_info/<int:user_id>/', blogviews.user_detail, name='user_detail'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.

class ArticlePost(models.Model):
    """
    文章
    """
    author=models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE)
    title=models.CharField(verbose_name='标题',max_length=100)
    body=models.TextField(verbose_name='内瑞')
    created=models.DateTimeField(verbose_name='创建时间',default=timezone.now)
    updated=models.DateTimeField(verbose_name='更新时间',auto_now=True)
    total_views=models.PositiveIntegerField(verbose_name='点击量',default=0)
    class Meta:
        ordering=('-created',)
        verbose_name=verbose_name_plural='文章'
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    """
    文章评论
    """
    article=models.ForeignKey(ArticlePost,verbose_name='文章',on_delete=models.DO_NOTHING,related_name='comments')
    user=models.ForeignKey(User,verbose_name='发表人',on_delete=models.CASCADE,related_name='comments')
    body=models.TextField(verbose_name='内瑞',blank=False)
    pre_comment=models.ForeignKey('self',on_delete=models.DO_NOTHING,verbose_name='原评论',null=True)
    created=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    class Meta:
        ordering=('-created',)
        verbose_name=verbose_name_plural='评论'
    def __str__(self):
        return f'{self.body[:20]}'

class User_Info(models.Model):
    """
    个人首页信息
    """
    user=models.OneToOneField(User,verbose_name='账号',on_delete=models.CASCADE,related_name='user_info')
    img=models.ImageField(upload_to='image/user/%Y/%m/%d/',verbose_name='头像',default='image/user/default.png')
    phone=models.PositiveIntegerField(verbose_name='手机号码',blank=True,null=True)
    address=models.CharField(verbose_name='地址',max_length=200,blank=True)
    conditon=models.CharField(verbose_name='心情状态',max_length=20,blank=True,default='无')
    birthday=models.DateField(verbose_name='生日',default=timezone.now().date()-timedelta(days=20*365))
    class Meta:
        verbose_name=verbose_name_plural='个人主页信息'
    def __str__(self):
        return f'{self.user}'
    def get_age(self):
        return int((timezone.now().date()-self.birthday).days//365.25)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User_Info

class UserLoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(label='密码')

class UserRegisterForm(forms.ModelForm):
    password=forms.CharField(label='密码',required=True)
    password2=forms.CharField()
    class Meta:
        model=User
        fields=('username','email',)
    def clean_password(self):
        data=self.cleaned_data
        if data.get('password')==self['password2'].value():
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致!!!')

class User_detailForm(forms.ModelForm):
    class Meta:
        model=User_Info
        fields='__all__'
        exclude=['user']

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse_lazy
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.models import User
from .models import ArticlePost,Comment,User_Info
from django.core.paginator import Paginator
from .forms import UserLoginForm,UserRegisterForm,User_detailForm
from django.views import View

# Create your views here.
def article_list(request):
    # 根据get请求的查询条件返回
    if request.GET.get('order')=="total_views":
        article_list= ArticlePost.objects.order_by('-total_views')
        order='total_view'
    else:
        article_list=ArticlePost.objects.all()
        order='normal'
    paginater=Paginator(article_list,4)
    page=request.GET.get('page')
    articles=paginater.get_page(page)
    context={'articles':articles,'order':order}
    return render(request,'article/list.html',context)

@login_required(login_url=reverse_lazy('blog:user_login'))
def article_create(request):
    if request.method=='POST':
        title,body,author=request.POST.get('title'),request.POST.get('body'),request.user
        ArticlePost.objects.create(title=title,body=body,author=author)
        return redirect('blog:article_list')
    else:
        return render(request,'article/create.html')
# 详情
def article_detail(request,id):
    # article=ArticlePost.objects.get(id=id)
    article=get_object_or_404(ArticlePost,id=id)
    article.total_views+=1
    article.save(update_fields=['total_views'])
    # article.update(total_views=F('total_views')+1)
    comments=Comment.objects.filter(article=id)
    return render(request,'article/detail.html',{'article':article,'comments':comments})

def article_delete(request,id):
    article=ArticlePost.objects.get(id=id)
    article.delete()
    return redirect('blog:article_list')

# 更新
@login_required(login_url=reverse_lazy('blog:user_login'))
def article_update(request,id):
    article=ArticlePost.objects.get(id=id)
    if request.user!=article.author:
        return HttpResponse('您无权限删除此文章')
    if request.method=='POST':
        article.title,article.body=request.POST.get('title'),request.POST.get('body')
        article.save()
        return redirect('blog:article_detail',id=id)
    else:
        return render(request,'article/update.html',{'article':article})

# 评论
# @login_required(login_url='/userprofile/login/')
# def post_comment(request,article_id):
#     article=get_object_or_404(ArticlePost,id=article_id)
#     # print(request,request.user,request.POST)
#     if request.method=='POST':
#         body,user,pid=request.POST.get('body').strip(),request.user,request.POST.get('pid')
#         if body:
#             Comment.objects.create(article=article,body=body,user=user,pre_comment_id=pid)
#         return redirect('blog:article_detail',id=article_id)
#     else:
#         return HttpResponse('评论只接受POST请求')

# 评论后改为返回json
@login_required(login_url='/userprofile/login/')
def post_comment(request,article_id):
    article=get_object_or_404(ArticlePost,id=article_id)
    # print(request,request.user,request.POST)
    if request.method=='POST':
        body,user,pid=request.POST.get('body').strip(),request.user,request.POST.get('pid')
        if body:
            Comment.objects.create(article=article,body=body,user=user,pre_comment_id=pid)
        comment=list(Comment.objects.filter(article=article).values('id','article_id','user'))
        return JsonResponse(comment,safe=False)
    else:
        return HttpResponse('评论只接受POST请求')

# 用户
def user_login(request):
    if request.method=='POST':
        user_login_form=UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data=user_login_form.cleaned_data
            user=authenticate(username=data['username'],password=data['password'])
            if user:
                login(request,user)
                return redirect('blog:article_list')
            else:
                return HttpResponse('用户名或密码输入有误，请重新输入')
        else:
            return HttpResponse('用户名或密码输入不合法')
    elif request.method=='GET':
        return render(request,'userprofile/login.html',{'form':UserLoginForm()})

def user_logout(request):
    logout(request)
    return redirect('blog:article_list')

def user_register(request):
    if request.method=='POST':
        user_register_form=UserRegisterForm(data=request.POST)
        # print(request.POST,user_register_form.errors)
        if user_register_form.is_valid():
            user=user_register_form.save(commit=False)
            user.set_password(user_register_form.cleaned_data['password'])
            user.save()
            User_Info.objects.create(user=user)
            login(request,user)
            return redirect('blog:article_list')
        else:
            return HttpResponse('输入有误，请重新输入')
    elif request.method=='GET':
        return render(request,'userprofile/register.html',{'form':UserRegisterForm()})
    else:
        return HttpResponse('请使用GET或POST请求数据')

def user_detail(request,user_id):
    show_user=get_object_or_404(User,id=user_id)
    show_user_info=get_object_or_404(User_Info,user=show_user)
    show_user_form=User_detailForm(instance=show_user_info)
    return render(request,'userprofile/detail.html',locals())

blog/templates/userprofile/detail.html
{% extends 'base.html' %} {% load static %}
{% block title %}{{ user.username }}的个人主页{% endblock %}
{% block content %}
<div class="container">
    <div class="media badge-light">
        <div class="media-left media-middle">
            <a href="#">
                <img src="{{ show_user_info.img.url }}" class="media-object" height="120" width="80">
            </a>
        </div>
        <div class="media-body">
            <h4 class="media-heading">  {{ user.username }}的个人主页
            </h4>
            <p class="text-info">当前状态： {{ show_user_info.conditon }}</p>
            <p class="text-info">年龄：{{ show_user_info.get_age }}岁</p>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-12">
            <div class="card h-100 badge-light">
                <div class="card-body">
                    <h4 class="card-title  bi bi-clock">生日</h4>
                    <span>{{ show_user_info.birthday }}</span>
                </div>
            </div>
        </div>
    </div>
    <div class="row mt-2">
        <div class="col-sm-12">
            <div class="card h-100 badge-light">
                <div class="card-body">
                    <h4 class="card-title bi bi-house">地址</h4>
                    {% if show_user_info.address %}
                    <address>{{ show_user_info.address }}</address>
                    {% else %}
                    <address>未填写</address>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
        <div class="row mt-2">
        <div class="col-sm-12">
            <div class="card h-100 badge-light">
                <div class="card-body">
                    <h4 class="card-title bi bi-phone">手机号码</h4>
                    {% if show_user_info.phone %}
                    <address>{{ show_user_info.phone }}</address>
                    {% else %}
                    <address>未填写</address>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

blog/templates/userprofile/login.html
{% extends 'base.html' %} {% load static %}
{% block title %}登录{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 badge-secondary">
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username" autofocus>
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
                <button type="submit" class="btn-primary">登录</button>
                <br>
                <h5>还没有账号？</h5>
                <h5>点击<a href="{% url 'blog:user_register' %}">注册账号</a>加入我们吧</h5>
            </form>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/userprofile/register.html
{% extends 'base.html' %} {% load static %}
{% block title %}登录{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-6 badge-secondary">
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">账号</label>
                    <input type="text" class="form-control" id="username" name="username" required>
                </div>
                <div class="form-group">
                    <label for="email">邮箱</label>
                    <input type="text" class="form-control" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="password">密码</label>
                    <input type="password" class="form-control" id="password" name="password" required>
                </div>
                <div class="form-group">
                    <label for="password2">确认密码</label>
                    <input type="password" class="form-control" id="password2" name="password2" required>
                </div>
                <button type="submit" class="btn-primary">提交</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}