DjangoBlog/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from django.views.static import serve
from .settings import DEBUG,MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',include('blog.urls')),
]

if DEBUG:
    urlpatterns+=[
        re_path(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT})
    ]

blog/urls.py
from django.urls import path
from . import views as blogviews
from django.conf.urls import url

app_name='blog'
urlpatterns = [
    url(r'^$', blogviews.article_list),
    path('article_list/', blogviews.article_list,name='article_list'),
    path('article_create/', blogviews.article_create, name='article_create'),
    path('article_detail/<int:id>/', blogviews.article_detail, name='article_detail'),
    path('article_delete/<int:id>/', blogviews.article_delete, name='article_delete'),
    path('article_update/<int:id>/', blogviews.article_update, name='article_update'),

    path('post_comment/<int:article_id>/', blogviews.post_comment, name='post_comment'),

    path('user_login/', blogviews.user_login, name='user_login'),
    path('user_logout/', blogviews.user_logout, name='user_logout'),
    path('user_register/', blogviews.user_register, name='user_register'),
    path('user_info/<int:user_id>/', blogviews.user_detail, name='user_detail'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta

# Create your models here.

class ArticlePost(models.Model):
    """
    文章
    """
    author=models.ForeignKey(User,verbose_name='作者',on_delete=models.CASCADE)
    title=models.CharField(verbose_name='标题',max_length=100)
    body=models.TextField(verbose_name='内瑞')
    created=models.DateTimeField(verbose_name='创建时间',default=timezone.now)
    updated=models.DateTimeField(verbose_name='更新时间',auto_now=True)
    total_views=models.PositiveIntegerField(verbose_name='点击量',default=0)
    class Meta:
        ordering=('-created',)
        verbose_name=verbose_name_plural='文章'
    def __str__(self):
        return f'{self.title}'

class Comment(models.Model):
    """
    文章评论
    """
    article=models.ForeignKey(ArticlePost,verbose_name='文章',on_delete=models.DO_NOTHING,related_name='comments')
    user=models.ForeignKey(User,verbose_name='发表人',on_delete=models.CASCADE,related_name='comments')
    body=models.TextField(verbose_name='内瑞',blank=False)
    pre_comment=models.ForeignKey('self',on_delete=models.DO_NOTHING,verbose_name='原评论',null=True)
    created=models.DateTimeField(verbose_name='创建时间',auto_now_add=True)
    class Meta:
        ordering=('-created',)
        verbose_name=verbose_name_plural='评论'
    def __str__(self):
        return f'{self.body[:20]}'

class User_Info(models.Model):
    """
    个人首页信息
    """
    user=models.OneToOneField(User,verbose_name='账号',on_delete=models.CASCADE,related_name='user_info')
    img=models.ImageField(upload_to='image/user/%Y/%m/%d/',verbose_name='头像',default='image/user/default.png')
    phone=models.PositiveIntegerField(verbose_name='手机号码',blank=True,null=True)
    address=models.CharField(verbose_name='地址',max_length=200,blank=True)
    conditon=models.CharField(verbose_name='心情状态',max_length=20,blank=True,default='无')
    birthday=models.DateField(verbose_name='生日',default=timezone.now().date()-timedelta(days=20*365))
    class Meta:
        verbose_name=verbose_name_plural='个人主页信息'
    def __str__(self):
        return f'{self.user}'
    def get_age(self):
        return int((timezone.now().date()-self.birthday).days//365.25)

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import User_Info

class UserLoginForm(forms.Form):
    username=forms.CharField()
    password=forms.CharField(label='密码')

class UserRegisterForm(forms.ModelForm):
    password=forms.CharField(label='密码',required=True)
    password2=forms.CharField()
    class Meta:
        model=User
        fields=('username','email',)
    def clean_password(self):
        data=self.cleaned_data
        if data.get('password')==self['password2'].value():
            return data.get('password')
        else:
            raise forms.ValidationError('密码输入不一致!!!')

class User_detailForm(forms.ModelForm):
    class Meta:
        model=User_Info
        fields='__all__'
        exclude=['user']

blog/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate,login,logout
from django.urls import reverse_lazy
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.models import User
from .models import ArticlePost,Comment,User_Info
from django.core.paginator import Paginator
from .forms import UserLoginForm,UserRegisterForm,User_detailForm
from django.views import View

# Create your views here.
def article_list(request):
    # 根据get请求的查询条件返回
    if request.GET.get('order')=="total_views":
        article_list= ArticlePost.objects.order_by('-total_views')
        order='total_view'
    else:
        article_list=ArticlePost.objects.all()
        order='normal'
    paginater=Paginator(article_list,4)
    page=request.GET.get('page')
    articles=paginater.get_page(page)
    context={'articles':articles,'order':order}
    return render(request,'article/list.html',context)

@login_required(login_url=reverse_lazy('blog:user_login'))
def article_create(request):
    if request.method=='POST':
        title,body,author=request.POST.get('title'),request.POST.get('body'),request.user
        ArticlePost.objects.create(title=title,body=body,author=author)
        return redirect('blog:article_list')
    else:
        return render(request,'article/create.html')
# 详情
def article_detail(request,id):
    # article=ArticlePost.objects.get(id=id)
    article=get_object_or_404(ArticlePost,id=id)
    article.total_views+=1
    article.save(update_fields=['total_views'])
    # article.update(total_views=F('total_views')+1)
    comments=Comment.objects.filter(article=id)
    return render(request,'article/detail.html',{'article':article,'comments':comments})

def article_delete(request,id):
    article=ArticlePost.objects.get(id=id)
    article.delete()
    return redirect('blog:article_list')

# 更新
@login_required(login_url=reverse_lazy('blog:user_login'))
def article_update(request,id):
    article=ArticlePost.objects.get(id=id)
    if request.user!=article.author:
        return HttpResponse('您无权限删除此文章')
    if request.method=='POST':
        article.title,article.body=request.POST.get('title'),request.POST.get('body')
        article.save()
        return redirect('blog:article_detail',id=id)
    else:
        return render(request,'article/update.html',{'article':article})

# 评论
# @login_required(login_url='/userprofile/login/')
# def post_comment(request,article_id):
#     article=get_object_or_404(ArticlePost,id=article_id)
#     # print(request,request.user,request.POST)
#     if request.method=='POST':
#         body,user,pid=request.POST.get('body').strip(),request.user,request.POST.get('pid')
#         if body:
#             Comment.objects.create(article=article,body=body,user=user,pre_comment_id=pid)
#         return redirect('blog:article_detail',id=article_id)
#     else:
#         return HttpResponse('评论只接受POST请求')

# 评论后改为返回json
@login_required(login_url='/userprofile/login/')
def post_comment(request,article_id):
    article=get_object_or_404(ArticlePost,id=article_id)
    # print(request,request.user,request.POST)
    if request.method=='POST':
        body,user,pid=request.POST.get('body').strip(),request.user,request.POST.get('pid')
        if body:
            Comment.objects.create(article=article,body=body,user=user,pre_comment_id=pid)
        comment=list(Comment.objects.filter(article=article).values('id','article_id','user'))
        return JsonResponse(comment,safe=False)
    else:
        return HttpResponse('评论只接受POST请求')

# 用户
def user_login(request):
    if request.method=='POST':
        user_login_form=UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data=user_login_form.cleaned_data
            user=authenticate(username=data['username'],password=data['password'])
            if user:
                login(request,user)
                return redirect('blog:article_list')
            else:
                return HttpResponse('用户名或密码输入有误，请重新输入')
        else:
            return HttpResponse('用户名或密码输入不合法')
    elif request.method=='GET':
        return render(request,'userprofile/login.html',{'form':UserLoginForm()})

def user_logout(request):
    logout(request)
    return redirect('blog:article_list')

def user_register(request):
    if request.method=='POST':
        user_register_form=UserRegisterForm(data=request.POST)
        # print(request.POST,user_register_form.errors)
        if user_register_form.is_valid():
            user=user_register_form.save(commit=False)
            user.set_password(user_register_form.cleaned_data['password'])
            user.save()
            User_Info.objects.create(user=user)
            login(request,user)
            return redirect('blog:article_list')
        else:
            return HttpResponse('输入有误，请重新输入')
    elif request.method=='GET':
        return render(request,'userprofile/register.html',{'form':UserRegisterForm()})
    else:
        return HttpResponse('请使用GET或POST请求数据')

def user_detail(request,user_id):
    show_user=get_object_or_404(User,id=user_id)
    show_user_info=get_object_or_404(User_Info,user=show_user)
    show_user_form=User_detailForm(instance=show_user_info)
    return render(request,'userprofile/detail.html',locals())

blog/templates/article/create.html
{% extends 'base.html' %} {% load static %}
{% block title %}写文章{% endblock %}
{% block content %}
    <div class="container badge-secondary">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <textarea type="text" rows="12" class="form-control" id="body" name="body"></textarea>
                </div>
                <button type="submit" class="btn-primary">完成</button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/article/detail-bak.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
<div class="container" style="background: #bee5eb">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-primary">
            <a>作者：{{ article.author }}</a>
            <a>{{ article.created|date:'Y-m-d H:i:s' }}</a>
            <!-- 只有作者可以修改文章 -->
            {% if user == article.author %}
            · <a href="#" data-toggle="modal" data-target="#myModal">删除文章</a>
            · <a href="{% url "blog:article_update" article.id %}">编辑文章</a>
            {% endif %}
            <small class="col align-self-end" style="color: gray;">
                            <span class="bi bi-eye">
                            {{ article.total_views }}
                            </span>
            </small>
        </div>
        <!-- 文章正文 -->
        <div class="col-12">
            <pre class="text-lg-left">{{ article.body }}</pre>
        </div>
    </div>
</div>

    <div class="container">
        <div class="col-12">
    <!-- 发表评论 -->
    <hr>
    {% if user.is_authenticated %}
    <div>
        <form
                action="{% url 'blog:post_comment' article.id %}"
                method="POST"
        >
            {% csrf_token %}
            <div class="form-group form-inline">
                <label for="body">
                    <strong class="text-warning">
                        我也要发言：
                    </strong>
                </label>
                <textarea
                        type="text"
                        class="form-control"
                        id="body"
                        name="body"
                        cols="60"
                        rows="1">
                </textarea>
                <button type="submit" class="btn btn-primary">发送</button
            </div>
            <!-- 提交按钮 -->>
        </form>
    </div>
    <br>
    {% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'blog:user_login' %}">登录</a>后回复
    </h5>
    <br>
    {% endif %}
        </div>
    </div>

<div class="container">
    <div class="col-12">
<!-- 显示评论 -->
<h5>共有{{ comments.count }}条评论</h5>
<div >
    {% for comment in comments %}
    <hr>
    <p style="color: white">
<!--        <strong style="color: pink">-->
        <span class="bi bi-person" style="color: yellow">
            {{ comment.user }}
        </span>
        <!--        </strong> -->
        于
        <span style="color: yellow">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
    </p>
    <pre style="font-family: inherit; font-size: 1em; color:lightgray">
{{ comment.body }}</pre>
    {% endfor %}
</div>
</div>


<!-- 模态框 -->
<div class="modal fade " id="myModal">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <h4 class="modal-title">确认删除</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                确认删除文章？
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        onclick="confirm_delete()">
                确定
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
             location.href='{% url "blog:article_delete" article.id %}'
    }
</script>

{% endblock content %}

blog/templates/article/detail.html
<!-- extends表明此页面继承自 base.html 文件 -->
{% extends "base.html" %}
{% load static %}

<!-- 写入 base.html 中定义的 title -->
{% block title %}
文章详情
{% endblock title %}

<!-- 写入 base.html 中定义的 content -->
{% block content %}
<!-- 文章详情 -->
<div class="container" style="background: #bee5eb">
    <div class="row">
        <!-- 标题及作者 -->
        <h1 class="col-12 mt-4 mb-4">{{ article.title }}</h1>
        <div class="col-12 alert alert-primary">
            <a>作者：{{ article.author }}</a>
            <a>{{ article.created|date:'Y-m-d H:i:s' }}</a>
            <!-- 只有作者可以修改文章 -->
            {% if user == article.author %}
            · <a href="#" data-toggle="modal" data-target="#myModal">删除文章</a>
            · <a href="{% url "blog:article_update" article.id %}">编辑文章</a>
            {% endif %}
            <small class="col align-self-end" style="color: gray;">
                            <span class="bi bi-eye">
                            {{ article.total_views }}
                            </span>
            </small>
        </div>
        <!-- 文章正文 -->
        <div class="col-12">
            <pre class="text-lg-left">{{ article.body }}</pre>
        </div>
    </div>
</div>

    <div class="container">
        <div class="col-12">
    <!-- 发表评论 -->
    <hr>
    {% if user.is_authenticated %}
    <div>
        <div class="form-group form-inline">
            {% csrf_token %}
            <label for="body">
                <strong class="text-warning">
                    我也要发言：
                </strong>
            </label>
            <textarea
                        class="form-control"
                        id="body"
                        name="body"
                        cols="60"
                        rows="1"
                        placeholder="说点什么吧"></textarea>
            <button type="submit" id="post_comment" class="btn btn-primary">发送</button
            </div>

<!--        原提交评论后会刷新页面-->
<!--        <form-->
<!--                action="{% url 'blog:post_comment' article.id %}"-->
<!--                method="POST"-->
<!--        >-->
<!--            {% csrf_token %}-->
<!--            <div class="form-group form-inline">-->
<!--                <label for="body">-->
<!--                    <strong class="text-warning">-->
<!--                        我也要发言：-->
<!--                    </strong>-->
<!--                </label>-->
<!--                <textarea-->
<!--                        type="text"-->
<!--                        class="form-control"-->
<!--                        id="body"-->
<!--                        name="body"-->
<!--                        cols="60"-->
<!--                        rows="1"></textarea>-->
<!--                <button type="submit" class="btn btn-primary">发送</button-->
<!--            </div>-->
<!--            &lt;!&ndash; 提交按钮 &ndash;&gt;>-->
<!--        </form>-->
    </div>
    <br>
    {% else %}
    <br>
    <h5 class="row justify-content-center">
        请<a href="{% url 'blog:user_login' %}">登录</a>后回复
    </h5>
    <br>
    {% endif %}

        </div>

<!--原文的评论区域-->
<!--        <div class="comment_post">      {# 提交评论区域的div #}-->
<!--            <div id="commentform_title">发表评论</div>-->
<!--            <textarea rows="10" cols="60" id="comment_content"></textarea>-->
<!--            <p><button>提交评论</button></p>-->
<!--        </div>-->

    </div>

<div class="container">
    <div class="col-12">
<!-- 显示评论 -->
<h5>共有{{ comments.count }}条评论</h5>
<div id="comment_list">
    {% for comment in comments %}
    <hr>
    <p style="color: white">
<!--        <strong style="color: pink">-->
        <span class="bi bi-person" style="color: yellow">
            {{ comment.user }}
        </span>
        <!--        </strong> -->
        于
        <span style="color: yellow">
                    {{ comment.created|date:"Y-m-d H:i:s" }}
                </span> 时说：
    </p>
    <pre style="font-family: inherit; font-size: 1em; color:lightgray">
{{ comment.body }}  <button type="button" pk="{{ comment.user_id }}" username="{{ comment.user }}" class="reply btn-link">回复</></pre>
    {% endfor %}
</div>
</div>


<!-- 模态框 -->
<div class="modal fade " id="myModal">
    <div class="modal-dialog modal-dialog-centered modal-sm">
        <div class="modal-content">
            <!-- 模态框头部 -->
            <div class="modal-header">
                <h4 class="modal-title">确认删除</h4>
                <button type="button" class="close" data-dismiss="modal">&times;</button>
            </div>
            <!-- 模态框主体 -->
            <div class="modal-body">
                确认删除文章？
            </div>
            <!-- 模态框底部 -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal"
                        onclick="confirm_delete()">
                确定
                </button>
            </div>
        </div>
    </div>
</div>
<script>
    // 删除文章的函数
    function confirm_delete() {
             location.href='{% url "blog:article_delete" article.id %}'
    }
</script>

    <script>
        // 用于生成控件脚本的函数
        function makecomment(commentuser,commentdate,commentbody,commentid) {
            return  '<p style="color: white">\
                <!--        <strong style="color: pink">-->\
                <span class="bi bi-person" style="color: yellow">'+
                commentuser+
        '</span>\
            <!--        </strong> -->\
            于\
            <span style="color: yellow">'+
                commentdate+
        '</span> 时说：\
            </p>\
            <pre style="font-family: inherit; font-size: 1em; color:lightgray">'+
                commentbody+
                '<button type="button" pk="'+
                commentid+
                '"'+' username="'+commentuser+
                '" class="reply btn-link">回复</></pre>'
        }

        var pid = "";       // {# 设置一个变量pid默认为空，用于后面作为数据库存储的父级评论的ID，如果没有父级评论则为空，子评论有父级评论 #}
        // {# 提交评论按钮的点击事件 #}
        $("#post_comment").click(function (){
            // var body=$("#comment_content").val().replace(/^\s*|\s*$/g,"") // 去除两头空格
            var body=$("#body").val().trim()
            if(body===""){
                return;} //如果为空则不执行任何操作
            $.ajax({
                url: '{% url 'blog:post_comment' article.id %}',
                type: 'post',
                data: {
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                    body: body,    // {# 提交的数据内容data #}
                    pid: pid
                },
                success: function (res){         // {# 本例中返回的数据仅仅用于在控制台打印而已 #}
                console.log(res);                // {# 控制台打印返回的数据 #}
                    $("#body").val("");   // {# 提交完成后，清空评论输入框的内容 #}
                    pid = "";                        // {# 子评论提交完成后，将pid默认设置为空，恢复为默认的父评论 #}
                    $("#body").attr("placeholder","说点什么吧");
                    // alert(JSON.stringify(res));
                    $("#comment_list").prepend(makecomment("root",'202133',"hahaha","124556"))

                }
        })
        })


        // {# 回复按钮的点击事件 #}
        $(".reply").click(function (){
            $("#body").focus();       //{# 回复按钮的事件，点击时，将光标聚集到评论输入框中 #}
            var val = "@" + $(this).attr("username") + "\n";   // {# $(this)指代".reply"标签本身，获取这个标签的username值 #}
            // $("#body").val(val);      {# 回复时，自动在输入框加入：@要回复的人 #}
            $("#body").attr("placeholder",val);
            pid = $(this).attr("pk");           // {# 当点击回复时，父评论ID不再为空，此时修改为：对应评论的主键值ID #}
        })

    </script>

{% endblock content %}

blog/templates/article/list.html
{% extends 'base.html' %} {% load static %}
{% block title %}首页{% endblock %}
{% block content %}
<div class="container">
    <nav aria-label="bradcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="{% url 'blog:article_list' %}">最新</a>
            </li>
            <li class="breadcrumb-item">
                <a href="{% url 'blog:article_list' %}?order=total_views">最热</a>
            </li>
        </ol>
    </nav>
    {% for article in articles %}
    <div class="row mt-2">
        <div class="col-sm-12">
            <div class="card h-100 badge-light">
                <div class="card-body">
                    <h4 class="card-title">{{ article.title }}</h4>
                    <a href="{% url 'blog:article_detail' article.id %}" class="card-link">阅读本文</a>
                        <small class="col align-self-end" style="color:gray">
                            <span class="bi bi-eye">
                                {{ article.total_views }}
                            </span>
                        </small>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<div class="pagination row">
    <div class="m-auto">
        <span class="step-links">
            {% if articles.has_previous %}
            <a href="?page=1&order={{ order }}" class="btn btn-success">
                第1页
            </a>
<!--            <span>...</span>-->
            <a href="?page={{ articles.previous_page_number }}" class="btn btn-secondary">
                {{ articles.previous_page_number }}
            </a>
            {% endif %}

            <span class="current btn btn-danger btn-lg">
                {{articles.number}}
            </span>

            {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}&order={{ order }}" class="btn btn-success">
                {{ articles.next_page_number }}
            </a>
            <a href="?page={{ articles.paginator.num_pages }}&order={{ order }}" class="btn btn-success">
                最后1页
            </a>
            {% endif %}
        </span>
    </div>
</div>
<div class="text-warning text-center">
    共{{ articles.paginator.num_pages }}页
</div>
{% endblock %}

blog/templates/article/update.html
{% extends "base.html" %} {% load static %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title">文章标题</label>
                    <!-- 在 value 属性中指定文本框的初始值为旧的内容，即 article 对象中的 title 字段 -->
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>
                <div class="form-group">
                    <label for="body">文章正文</label>
                    <!-- 文本域不需要 value 属性，直接在标签体中嵌入数据即可 -->
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>
                <button type="submit" class="btn btn-primary">完成</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}